### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sanonekojita** [sanonekojita/furima-40014#20]
# 自身のフリマアプリのURL
https://furima-40014.onrender.com

# Basic認証のIDとパスワード
ID：admin
パスワード：2222
	
# 出品者用のメールアドレスとパスワード
メールアドレス：ggg@ggg
パスワード：ggggg9

# 購入者用のメールアドレスとパスワード
メールアドレス：aaa@aaa
パスワード：aaaaa9

**Comment by snkw-works** [comment]
@sanonekojita さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [x] **発送元の地域は、「---」と47都道府県の合計48項目が表示されるよう修正しましょう（--- は初期値として設定すること）**
「山口県」が抜けている状態です。

- [x] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう**
入力に問題がある状態で出品ボタンをクリックした後の画面で「販売手数料」「販売利益」が表示されなくなってしまいます。どの状態でも表示されるよう修正しましょう。

#### 商品購入機能
- [x] **商品購入ページにて、クレジットカードの情報が入力できるよう修正しましょう**
現在、クレジットカードの情報入力欄は表示されていますが、カーソルを合わせても入力ができない状態です。
※リロードすると入力可能な状態になります。購入画面に遷移した時に、リロードしなくても入力できる状態となるよう、修正しましょう。

https://github.com/sanonekojita/furima-40014/assets/54050089/05e95617-8779-427c-93d3-c5e480d430cc


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sanonekojita** [comment]
動作確認ありがとうございました！
修正したのでフォーム提出させていただきます。

**Comment by snkw-works** [comment]
@sanonekojita さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by sanonekojita** [comment]
ありがとうございました！
